"""
gain_calculations.py
--------------------

Calculates gain generated by
possible actions.

Contains calculations only.

No ETL.
No DataFrames.
No file operations.
"""

from core_metrics import (
    mining_rate,
    ship_speed,
    cargo,
)

# ==========================================================
# EFFICIENCY
# ==========================================================


def efficiency(mining_rate_value: float, trip_time: float, cargo_value: float) -> float:
    """
    Ore produced during a trip
    divided by cargo capacity.
    """

    return (mining_rate_value * trip_time) / cargo_value


# ==========================================================
# DEPOSIT
# ==========================================================


def deposit(
    mining_rate_value: float,
    cargo_value: float,
    trip_time: float,
    efficiency_value: float,
) -> float:
    """
    Deposit per trip.

    If efficiency < 100%,
    the mining rate is the bottleneck,
    so the trip yields mining_rate * trip_time.

    If efficiency >= 100%,
    the cargo hold fills and the trip yields cargo capacity.
    """

    if efficiency_value < 1:

        return mining_rate_value * trip_time

    return cargo_value


# ==========================================================
# GAIN
# ==========================================================


def gain(
    current_deposit: float, projected_deposit: float, planet_worth: float
) -> float:
    """
    Credits/sec gained
    from an action.
    """

    return (projected_deposit - current_deposit) * planet_worth


# ==========================================================
# UNLOCK PLANET
# ==========================================================


def unlock_gain(distance: float, planet_worth: float) -> float:
    """
    Gain from unlocking
    a new planet.

    Defaults:
        Mining Rate = 0.25
        Ship Speed = 1
        Cargo = 5
    """

    mining = 0.25

    speed = 1.0

    cargo_value = 5

    trip_time = (distance * 2) / speed

    eff = efficiency(mining, trip_time, cargo_value)

    projected_deposit = deposit(mining, cargo_value, trip_time, eff)

    return projected_deposit * planet_worth


# ==========================================================
# MINING UPGRADE
# ==========================================================


def mining_upgrade_gain(
    mining_level: int,
    cargo_value: float,
    trip_time: float,
    current_deposit: float,
    planet_worth: float,
) -> float:
    """
    Gain from Mining +1.
    """

    projected_mining_rate = mining_rate(mining_level + 1)

    projected_eff = efficiency(projected_mining_rate, trip_time, cargo_value)

    projected_deposit = deposit(
        projected_mining_rate, cargo_value, trip_time, projected_eff
    )

    return gain(current_deposit, projected_deposit, planet_worth)


# ==========================================================
# SPEED UPGRADE
# ==========================================================


def speed_upgrade_gain(
    mining_rate_value: float,
    speed_level: int,
    cargo_value: float,
    distance: float,
    current_deposit: float,
    planet_worth: float,
) -> float:
    """
    Gain from Speed +1.
    """

    projected_speed = ship_speed(speed_level + 1)

    projected_trip_time = (distance * 2) / projected_speed

    projected_eff = efficiency(mining_rate_value, projected_trip_time, cargo_value)

    projected_deposit = deposit(
        mining_rate_value, cargo_value, projected_trip_time, projected_eff
    )

    return gain(current_deposit, projected_deposit, planet_worth)


# ==========================================================
# CARGO UPGRADE
# ==========================================================


def cargo_upgrade_gain(
    mining_rate_value: float,
    cargo_level: int,
    trip_time: float,
    current_deposit: float,
    planet_worth: float,
) -> float:
    """
    Gain from Cargo +1.
    """

    projected_cargo = cargo(cargo_level + 1)

    projected_eff = efficiency(mining_rate_value, trip_time, projected_cargo)

    projected_deposit = deposit(
        mining_rate_value, projected_cargo, trip_time, projected_eff
    )

    return gain(current_deposit, projected_deposit, planet_worth)
